spotpy/parameter.py

Revert "Parameter distributions"

---

spotpy/parameter.py

implemented args also

---

README.md
spotpy/algorithms/__init__.py
spotpy/algorithms/abc.py
spotpy/algorithms/fscabc.py

I added an implementation of ABC by Karaboga and FSCABC by Zhang.

Abc fscabc

---

spotpy/algorithms/mc.py

Fixed issue #22, repeater of the Monte Carlo loop needs to be terminated as in the other algorithms.

Issue #22: Fixed remaining processes in mc with MPI.

---

spotpy/algorithms/_algorithm.py
spotpy/algorithms/abc.py
spotpy/algorithms/demcz.py
spotpy/algorithms/fast.py
spotpy/algorithms/fscabc.py
spotpy/algorithms/lhs.py
spotpy/algorithms/mc.py
spotpy/algorithms/mcmc.py
spotpy/algorithms/mle.py
spotpy/algorithms/rope.py
spotpy/algorithms/sa.py
spotpy/algorithms/sceua.py
spotpy/database.py
spotpy/objectivefunctions.py
spotpy/parameter.py

- applied PEP8 style conventions to edited files
- modified the behaviour of the database class and its subclasses
(including possible custom ones)
- simulation results can now be multidimensional (numpy arrays) and
singularly nested lists
- database initialization is moved from mc and lhs algorithms and is now
solely performed when initializing the _algorithm class
- performance of ram and csv class is improved as the type checking
of likelihood and simulation data is done during initializing and is thus
taken out of the save method
- following this, all algorithms now send the same types of data to the
database.save method (i.e. usually 1d numpy array for likelihood and
simulations as defined in model.simulation (can be scalar, list,
nested list, any numpy array) at each call
- …

allow for multi_dim simulation results to be handled by database

---

spotpy/analyser.py

Error Handling on get_maxlikeindex and get_minlikeindex

---

spotpy/analyser.py

Standard value of like_index should be 1, as standard like is also called like1

Adapt get_sensitivity_of_fast to standard value of like

---

spotpy/examples/tutorial_signatures.py
spotpy/signatures.py

Now you can plot the raw data as this:
`vals = sig.getAverageFloodFrequencyPerSection(simulation, observation,datetime_series=dd_daily,threshold_value=1,mode="get_raw_data")
`
and
`vals.plot()`

Raw data as pandas object and threshold_factor to threshold_value

---

spotpy/algorithms/rope.py

Now the algorithm can be started with different values for the first and the following subsets, the percentages of the first and the following substes and the size of NDIR. Also a few errors are raised when the input is illogical and the layout was brought more in line with PEP8.

Allowed a more finely grained operation of the algorithms

---

spotpy/algorithms/rope.py

When calculating the first batch of new parameters after the first run, the wrong percentage was used.

Fixed minor bug with percentages

---

spotpy/algorithms/_algorithm.py
spotpy/algorithms/fscabc.py
spotpy/algorithms/sceua.py

Hi, 
Continuing on the work of @p-lauer I was able to add a restart functionality to sceua.py.
Thereby I also improved the read_breakdata and write_breakdata functions in _algorithm.py to improve their import functionality. I have already tested these changes on my machine (commit 
0c8851c) and would be really happy if you could accept them into master. I am in direct contact with p-lauer as well and we are using Spotpy towards a wrapper tool that we are creating.
Thank you.

Change to add restart functionality towards sceua.py (Issue #36)

---

spotpy/algorithms/sceua.py
spotpy/database.py

spotpy: set buffersize to text line in write of dbfile; included breakpoint in while loop in sceua.py

write dbfile and breakpoint at run time in unix

---

spotpy/algorithms/rope.py

- fixing ROPE if sample size is little

---

spotpy/algorithms/rope.py
spotpy/examples/spot_setup_standardnormal.py
spotpy/examples/tutorial_likelihood.py

Just some random minor fixes.
Just as a side note, I would love to make some more significant contributions to this project, and so if there is anything low-medium priority in the pipeline that you don't have time to pick up, I am more than happy to take that up 😄

Minor fixes

---

spotpy/analyser.py

Some errors that would not work if the respective code was run.
Ignore the whitespace differences.
Important changes on L320, L791, L810, L988

Fix minor errors in analyzer.py

---

spotpy/examples/tutorial_rosenbrock.py

The algorithms list had a missing value, which would cause the script to
error out.
Let me know if you want me to comment out the plot function again.

Fix Rosenbrock tutorial

---

spotpy/examples/spot_setup_cmf1d.py
spotpy/examples/spot_setup_standardnormal.py

- Missing self for accessing std
- spotpy.parameter instead of parameters

Fix minor errors in examples

---

.coveragerc
.travis.yml
README.md
spotpy/examples/spot_setup_hymod_python.py
spotpy/likelihoods.py
spotpy/unittests/fail_objectivefunctions.py
spotpy/unittests/fail_parallel.py
spotpy/unittests/test_database.py
spotpy/unittests/test_likelihood.py
spotpy/unittests/test_objectivefunctions.py
spotpy/unittests/test_signatures.py

- I also added a unittest and moved another which failed on travis, we have to fix that soon, too

Let coveralls.io cover more lines by using unittest

---

spotpy/algorithms/_algorithm.py

Fix IO Error in python2.7

---

spotpy/parameter.py

Fixed #111

---

spotpy/examples/tutorial_cmf_lumped.py
spotpy/parameter.py

The tutorial for a cmf lumped model had a mismatch between evaluation and simulation dates leading to low efficiancies. Fixed.

Tutorial cmf lumped

---

spotpy/parameter.py
spotpy/unittests/test_parameter.py
spotpy/unittests/testutils.py

Some more tests for the various parameter distributions.
These are majorly statistical tests, i.e. ensuring that a large enough sample from the distribution has correct mean and variance.

Parameter tests

---

.travis.yml
spotpy/examples/tutorial_cmf_lumped.py
spotpy/parameter.py
spotpy/unittests/test_parameter.py
spotpy/unittests/test_setup_parameters.py

Refactored the hard to understand _get_name_from_args function into a class _ArgumentHelper. That class and the methods are documented - hopefully the docstrings transport the basic idea behind that code part. Extended test_parameter.py to test the specific functionality.

Issue #109

---

.travis.yml
spotpy/algorithms/_algorithm.py
spotpy/algorithms/rope.py
spotpy/describe.py
spotpy/parameter.py
spotpy/unittests/test_describe.py

Added testing for describe module and fixed some Python 2 problems

Py2 unicode description

---

spotpy/unittests/test_likelihood.py

- make the test deterministic
- using a seed
- thanks to @philippkraft 
- #118

#118 add a seed for the test_likelihood.py - unittest 

---

spotpy/algorithms/sceua.py

I've been using Spotpy to calibrate a MODFLOW groundwater model using SCE-UA, and found these progress messages useful to understand at what stage of the algorithm we are at

add messages for SCE-UA progress console

---

spotpy/algorithms/_algorithm.py

This variable allows to define a starting number for random processes to make the predictable.

Included a random state variable

---

spotpy/unittests/test_analyser.py
spotpy/unittests/test_database.py

Test cleanup

---

setup.py

Following the inclusion of .hydrology from @philippkraft's fork (#150), this commit updates setup.py to include .hydrology in the list of packages.

Add .hydrology to the list of packages in setup.py

---

spotpy/hydrology/signatures.py

so it is in line with the other signatures

Changed the formatting of get_zero_q_freq 

---

spotpy/hydrology/signatures.py

The old signatures failed with rivers that had a discharge of 0 for at least 1/3 of the time. I tried to fix this and it is working now. It would be very helpful though if someone with a deeper mathmatetical knowledge could take a look at this.

Modified signatures for very low discharge rivers

---

spotpy/algorithms/_algorithm.py
spotpy/database.py

This is an improved version of our proposal to fix the restart issue #158. 
A second variable was introduced to better distinguish between different "states" for the data base (CSV) file handling. 
After the above was implemented, we found another issue with the function that checks if the data base needs to be created or if new lines shall be appended. 
Please let me know what you think of this proposed fix.

Improved proposal to fix issue #158

---

.travis.yml
spotpy/algorithms/__init__.py
spotpy/algorithms/_algorithm.py
spotpy/algorithms/abc.py
spotpy/algorithms/demcz.py
spotpy/algorithms/dream.py
spotpy/algorithms/fast.py
spotpy/algorithms/fscabc.py
spotpy/algorithms/list_sampler.py
spotpy/algorithms/mc.py
spotpy/algorithms/mle.py
spotpy/algorithms/rope.py
spotpy/algorithms/sa.py
spotpy/algorithms/sceua.py
spotpy/unittests/mpitest.sh
spotpy/unittests/test_algorithms.py
spotpy/unittests/test_setup_parameters.py

This pull request changes the total amount of repetitions for dream, rope, demcz, sceua, abc and fscabc. All algorithms will be forced to stop after the given number of repetitions.

Unifies the repetitions sampled by the algorithms

---

spotpy/algorithms/_algorithm.py
spotpy/gui/mpl.py
spotpy/parameter.py
spotpy/unittests/test_setup_parameters.py

parameter.ParameterSet replaces namedtuple as algorithm.partype

Added a Pickable replacement for the namedtuple

---

spotpy/algorithms/_algorithm.py

Updated the statistics output after backup and restart for best like, iteration and estimated runtime

Updated the statistics output

---

spotpy/examples/hymod_unix/hymod_cython/hymod.pyx
spotpy/examples/hymod_unix/hymod_cython/main_hymod.cpp

not to merge yet, first we nee to test

work around to not use the __file__ constant

---

pyproject.toml
setup.py

Solves issue mentioned in #287

Setup: remove setup.py since setuptools 64 supports pep660 now
